import { StyleSheet, Platform } from "react-native";
import {
    width,
    height,
    scale,
    verticalScale,
    moderateScale,
    isTablet,
} from "../../../utils/dimensions";
export default StyleSheet.create({
    gradient: {
        flex: 1,
    },
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: verticalScale(70),
    },
    logo: {
        width: isTablet ? scale(180) : scale(160),
        height: isTablet ? scale(180) : scale(160),
        marginBottom: verticalScale(10),
        marginTop: verticalScale(40),
    },
    FormContainer:{
        flex:1,
        padding: 35,
        borderRadius: 45,
        backgroundColor: 'white',
        width: width,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    title: {
        fontSize: isTablet ? moderateScale(38) : moderateScale(24),
        fontWeight: 'bold',
        color: '#00DB83',
        marginBottom: moderateScale(10),
        textAlign: 'center',
    },
    inputGroup: {
        width: '100%',
        marginBottom: 15,
    },
    label: {
        fontSize: isTablet ? moderateScale(18) : moderateScale(16),
        fontWeight: '600',
        color: '#333',
        marginBottom: 5,
        marginLeft: 5,
    },
    textInput: {
        outlineStyle: "none",
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#E9ECEF',
        borderRadius: 15,
        paddingHorizontal: 18,
        paddingVertical: 12,
        fontSize: 16,
        lineHeight: 22,
        color: '#333',
        width: '100%',
        minHeight: 48,
    },

    phoneInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#E9ECEF',
        borderRadius: 15,
        overflow: 'hidden',
        height:50,
    },
    countrySelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E9ECEF',
        paddingHorizontal: 15,
        borderRightWidth: 1,
        borderRightColor: '#DEE2E6',
        height:'100%'
    },
    countryFlag: {
        fontSize: 16,
        marginRight: 8,
    },
    countryCodeText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    phoneInput: {
        outlineStyle: "none",
        flex: 1,
        padding: 18,
        fontSize: 16,
        color: '#333',
    },
    phoneHint: {
        fontSize: 12,
        color: '#666',
        marginTop: 5,
        marginLeft: 5,
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#E9ECEF',
        borderRadius: 15,
        overflow: 'hidden',
        height:50,
    },
    passwordInput: {
        flex: 1,
        padding: 18,
        fontSize: 16,
        color: '#333',
    },
    eyeIcon: {
        padding: 10,
    },

    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 20,
        width: '90%',
        maxHeight: '70%',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 15,
        textAlign: 'center',
        color: '#00DB83',
    },
    countryItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    countryName: {
        flex: 1,
        fontSize: 16,
        marginLeft: 10,
    },
    countryDialCode: {
        fontSize: 16,
        color: '#666',
    },
    closeButton: {
        backgroundColor: '#00DB83',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 10,
    },
    closeButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    primaryButton: {
        borderRadius: 25,
        width: '100%',
        marginTop: 15,
        marginBottom: 25,
        overflow: 'hidden',
    },
    gradientButton: {
        padding: 18,
        alignItems: 'center',
        borderRadius: 25,
    },
    primaryButtonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
    },
    loginContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loginText: {
        color: '#666',
        fontSize: 16,
    },
    loginLink: {
        color: '#00DB83',
        fontSize: 16,
        fontWeight: 'bold',
        textDecorationLine: 'underline',
    },
});