import { StyleSheet, Platform } from "react-native";
import {
    height,
    scale,
    verticalScale,
    moderateScale,
    isTablet,
} from "../../utils/dimensions";

export default StyleSheet.create({
    gradient: {
        flex: 1,
    },
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: verticalScale(150),
    },
    logo: {
        width: isTablet ? scale(180) : scale(160),
        height: isTablet ? scale(180) : scale(160),
        marginBottom: verticalScale(10),
        marginTop: verticalScale(40),
    },
    textContainer: {
        alignItems: 'center',
        flex: 1,
    },
    title: {
        textAlign: 'center',
        fontSize: isTablet ? moderateScale(38) : moderateScale(32),
        fontWeight: "bold",
        color: 'white',
        marginBottom: verticalScale(15),
        textShadowColor: 'rgba(0, 0, 0, 0.1)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    slogan: {
        fontStyle: 'italic',
        fontSize: isTablet ? moderateScale(16) : moderateScale(14),
        color: 'white',
        textAlign: 'center',
        marginBottom: verticalScale(10),
        lineHeight: moderateScale(20),
        opacity: 0.9,
    },
    actionCard: {
        alignItems: 'center',
        backgroundColor: 'white',
        paddingVertical: verticalScale(50),
        paddingHorizontal: moderateScale(25),
        width: '100%',
        borderTopLeftRadius: moderateScale(45),
        borderTopRightRadius: moderateScale(45),
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -8 },
        shadowOpacity: 0.15,
        shadowRadius: 20,
        elevation: 10,
        height: height * 0.4
    },
    primaryButton: {
        borderRadius: moderateScale(25),
        marginBottom: verticalScale(35),
        overflow: 'hidden',
        shadowColor: '#00DB83',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
        width: '100%',
    },
    gradientButton: {
        paddingVertical: verticalScale(16),
        paddingHorizontal: moderateScale(20),
        borderRadius: moderateScale(25),
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: verticalScale(56),
    },
    secondaryButton: {
        borderWidth: 2,
        borderColor: '#00DB83',
        borderRadius: moderateScale(25),
        paddingVertical: verticalScale(16),
        paddingHorizontal: moderateScale(20),
        width: '100%',
        marginBottom: verticalScale(25),
        backgroundColor: 'white',
        minHeight: verticalScale(56),
        justifyContent: 'center',
    },
    secondaryButtonInner: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    primaryButtonText: {
        color: 'white',
        fontSize: isTablet ? moderateScale(18) : moderateScale(16),
        fontWeight: 'bold',
        marginLeft: moderateScale(8),
    },
    secondaryButtonText: {
        fontSize: isTablet ? moderateScale(18) : moderateScale(16), // Même taille
        color: '#00DB83',
        fontWeight: 'bold',
    },
    separator: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: verticalScale(15),
        width: '100%',
    },
    separatorLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#E9ECEF',
    },
    separatorText: {
        color: '#666',
        fontSize: moderateScale(12),
        fontWeight: '600',
        marginHorizontal: moderateScale(8),
        fontStyle: 'italic',
    },
    policyButton: {
        marginBottom: verticalScale(10),
        padding: moderateScale(8),
    },
    policyContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'wrap',
    },
    policyText: {
        color: '#1D3937',
        fontStyle: 'italic',
        fontSize: moderateScale(12),
        textAlign: 'center',
        marginLeft: moderateScale(5),
        textDecorationLine: 'underline',
        flexShrink: 1,
    },
    ecoBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 219, 131, 0.1)',
        paddingHorizontal: moderateScale(10),
        paddingVertical: moderateScale(5),
        borderRadius: moderateScale(12),
        borderWidth: 1,
        borderColor: 'rgba(0, 219, 131, 0.2)',
        marginTop: verticalScale(5),
    },
    ecoBadgeText: {
        color: '#00DB83',
        fontSize: moderateScale(10),
        fontWeight: '600',
        marginLeft: moderateScale(4),
    },
});