import {Dimensions, StyleSheet} from "react-native";

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    gradient: {
        flex: 1,
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingVertical: 20,
    },
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: height - 40,
    },
    logo: {
        width: 240,
        height: 240,
    },
    textContainer: {
        alignItems: 'center',
        marginBottom: 30,
        paddingHorizontal: 20,
    },
    title: {
        textAlign: 'center',
        fontSize: 42,
        fontWeight: "bold",
        color: 'white',
        marginBottom: 15,
        textShadowColor: 'rgba(0, 0, 0, 0.1)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    slogan: {
        fontStyle: 'italic',
        fontSize: 16,
        color: 'white',
        textAlign: 'center',
        marginBottom: 8,
        lineHeight: 22,
        opacity: 0.9,
    },
    actionCard: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
        width: width * 0.3,
        paddingVertical: 35,
        paddingHorizontal: 25,
        borderRadius: 35,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 20,
        elevation: 10,
    },
    primaryButton: {
        borderRadius: 25,
        marginBottom: 15,
        overflow: 'hidden',
        shadowColor: '#00DB83',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
        width:'100%',
        borderWidth: 2,
        borderColor: '#00DB83',
    },
    gradientButton:{
        width:'100%',
        height:'100%',
        paddingVertical: 18,
        paddingHorizontal: 0,
    },
    secondaryButton: {
        borderWidth: 2,
        borderColor: '#00DB83',
        borderRadius: 25,
        paddingVertical: 18,
        paddingHorizontal: 30,
        marginBottom: 20,
        backgroundColor: 'white',
        width:'100%',
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    primaryButtonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 10,
    },

    secondaryButtonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    secondaryButtonText: {
        fontSize: 16,
        color: '#00DB83',
        fontWeight: 'bold',
        marginLeft: 8,
        textAlign:'center',
    },
    separator: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 15,
        width: '100%',
    },
    separatorLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#E9ECEF',
    },
    separatorText: {
        color: '#666',
        fontSize: 12,
        fontWeight: '600',
        marginHorizontal: 10,
        fontStyle: 'italic',
    },
    policyButton: {
        marginBottom: 15,
        padding: 10,
    },
    policyContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    policyText: {
        color: '#1D3937',
        fontStyle: 'italic',
        fontSize: 12,
        textAlign: 'center',
        marginLeft: 6,
        textDecorationLine: 'underline',
    },
    ecoBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 219, 131, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: 'rgba(0, 219, 131, 0.2)',
    },
    ecoBadgeText: {
        color: '#00DB83',
        fontSize: 11,
        fontWeight: '600',
        marginLeft: 5,
    },
});